export const images = [
  {
    id: 1,
    image: require('../assets/images/syqypv1486981727.jpg'),
    title: '이미지1',
    release: '2023',
    languages: 'English',
    genre: 'Action',
  },
  {
    id: 2,
    image: require('../assets/images/sywswr1511383814.jpg'),
    title: '이미지2',
    release: '2023',
    languages: 'English',
    genre: 'Action',
  },
  {
    id: 3,
    image: require('../assets/images/ywwrsp1511720277.jpg'),
    title: '이미지3',
    release: '2023',
    languages: 'English',
    genre: 'Action',
  },
  {
    id: 4,
    image: require('../assets/images/vdwloy1713225718.jpg'),
    title: '이미지4',
    release: '2023',
    languages: 'English',
    genre: 'Action',
  },
  {
    id: 5,
    image: require('../assets/images/wyrqqq1468233628.jpg'),
    title: '이미지5',
    release: '2023',
    languages: 'English',
    genre: 'Action',
  },
];
